# Copyright 2021 IBM Corporation
# 
# Licensed under the Apache License, Version 2.0 (the "License"); 
# you may not use this file except in compliance with the License. 
# You may obtain a copy of the License at 
# 
#     http://www.apache.org/licenses/LICENSE-2.0 
# 
# Unless required by applicable law or agreed to in writing, software 
# distributed under the License is distributed on an "AS IS" BASIS, 
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
# See the License for the specific language governing permissions and 
# limitations under the License. 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: knative-deploy-controller
  labels:
    app: knative-deploy-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: knative-deploy-controller
  template:
    metadata:
      labels:
        app: knative-deploy-controller
    spec:
      serviceAccountName: default-admin
      containers:
      - name: knative-deploy-controller
        imagePullPolicy: Always
        image: aipipeline/deployment-knative-remote
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: knative-deploy-controller
  labels:
    app: knative-deploy-controller
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: knative-deploy-controller
  type: NodePort
